// Contenido literal del ANEXO I: MANUAL DE HERRAMIENTAS DE DISEÑO SOSTENIBLE
// "Estrategias proyectuales para la eficiencia energética en viviendas unifamiliares:
//  bases para un manual abierto de buenas prácticas. Caso: San Carlos Centro."
// Tesis de graduación FADU|UNL — Dona Luciano | Ramira Camila

// Sponsors / instituciones que apoyan el proyecto.
// Para sumar uno nuevo: agregar el PNG (fondo transparente) en assets/sponsors/
// y una línea acá con { name, img, url (opcional) }.
const SPONSORS = [
  { name: 'Universidad Nacional del Litoral', img: 'assets/sponsors/unl.png', url: 'https://www.unl.edu.ar/' },
];

const CATEGORIES = {
  EN: { num: '01', name: 'ENTORNO', tag: '[EN]', type: 'pasiva', color: '#7ca23c' },
  T:  { num: '02', name: 'TIPOLOGÍAS', tag: '[T]', type: 'pasiva', color: '#c3b143' },
  EV: { num: '03', name: 'ENVOLVENTES', tag: '[EV]', type: 'pasiva', color: '#55b8e4' },
  P:  { num: '04', name: 'SISTEMAS DE CONTROL Y PROTECCIÓN', tag: '[P]', type: 'pasiva', color: '#e56f2c' },
  SC: { num: '05', name: 'SISTEMAS COMPLEMENTARIOS', tag: '[SC]', type: 'pasiva', color: '#b28c9e' },
  AE: { num: '06', name: 'ARTEFACTOS EFICIENTES', tag: '[AE]', type: 'activa', color: '#5fbd8b' },
  ER: { num: '07', name: 'ENERGÍAS RENOVABLES', tag: '[ER]', type: 'activa', color: '#ef615e' },
  RH: { num: '08', name: 'GESTIÓN DEL RECURSO HÍDRICO', tag: '[RH]', type: 'activa', color: '#2d4a63' },
};

const STRATEGIES = [
  // ============ 01 | ENTORNO [EN] ============
  { code: 'EN01', cat: 'EN', group: 'Emplazamiento e implantación', title: 'RELACIÓN CON LINDEROS',
    text: 'Considerar escala, preexistencias y el impacto de posibles construcciones vecinas sobre el asoleamiento, ventilación.' },
  { code: 'EN02', cat: 'EN', group: 'Emplazamiento e implantación', title: 'CONSIDERACIÓN DE LAS MEDIDAS DEL LOTE',
    text: 'Evaluar cuáles son los lugares más adecuados para aprovechar ganancias solares según las dimensiones del lote.' },
  { code: 'EN03', cat: 'EN', group: 'Emplazamiento e implantación', title: 'ESPACIOS INTERMEDIOS',
    text: 'Incorporar galerías, patios y semicubiertos como espacios intermedios, reguladores climáticos entre interior y exterior.' },
  { code: 'EN04', cat: 'EN', group: 'Emplazamiento e implantación', title: 'RETIROS URBANOS',
    text: 'Incorporar retiros que amplíen la relación entre vivienda y la calle, favoreciendo una mejor calidad ambiental en el espacio público.' },
  { code: 'EN05', cat: 'EN', group: 'Asoleamiento', title: 'ORIENTACIÓN NORTE',
    text: 'Orientar aventanamientos y superficies al norte permitiendo tener mejor control del asoleamiento en diferentes estaciones.' },
  { code: 'EN06', cat: 'EN', group: 'Asoleamiento', title: 'ORIENTACIÓN ESTE',
    text: 'Orientar las aberturas hacia el este en ambientes de uso diurno, favoreciendo el ingreso de luz natural y el asoleamiento durante las mañanas.' },
  { code: 'EN07', cat: 'EN', group: 'Asoleamiento', title: 'EJE LONGITUDINAL ESTE-OESTE',
    text: 'Disponer siempre que sea posible el volumen sobre su eje mayor este–oeste para obtener ganancias solares pasivas sobre la fachada norte.' },
  { code: 'EN08', cat: 'EN', group: 'Asoleamiento', title: 'CONTROL OESTE',
    text: 'Minimizar superficies expuestas al oeste para disminuir la incidencia de radiación solar y controlar el asoleamiento.' },
  { code: 'EN09', cat: 'EN', group: 'Asoleamiento', title: 'CONTROL SUR',
    text: 'Garantizar una correcta aislación, continuidad de la envolvente, reduciendo las superficies vidriadas en función de los fuertes vientos y la incidencia solar.' },
  { code: 'EN10', cat: 'EN', group: 'Ventilación', title: 'VENTILACIÓN CRUZADA',
    text: 'Disponer aberturas enfrentadas en orientaciones opuestas que favorezcan la circulación continua.' },
  { code: 'EN11', cat: 'EN', group: 'Ventilación', title: 'VENTILACIÓN SELECTIVA',
    text: 'Ubicar aberturas a distintas alturas para favorecer la extracción del aire caliente por convección natural.' },
  { code: 'EN12', cat: 'EN', group: 'Ventilación', title: 'EFECTO CHIMENEA',
    text: 'Incorporar conductos verticales para la extracción del aire caliente mediante diferencia térmica y presión ascendente.' },
  { code: 'EN13', cat: 'EN', group: 'Ventilación', title: 'DEFLECTORES DE VIENTO',
    text: 'Cuando la ventilación cruzada no sea posible, integrar elementos salientes laterales en aberturas para aumentar la velocidad del viento por diferencia de presión.',
    tip: 'Estrategias de ventilación unilateral (EN13) que según la disposición de ventanas y elementos logran incrementar la velocidad interior (Vi) del aire hasta un 35%.' },

  // ============ 02 | TIPOLOGÍAS [T] ============
  { code: 'T01', cat: 'T', group: 'Consideraciones generales', title: 'LOCALES SERVIDOS AL NORTE',
    text: 'Priorizar espacios principales hacia el norte para aprovechar ganancias solares y controles solares.' },
  { code: 'T02', cat: 'T', group: 'Consideraciones generales', title: 'NÚCLEOS AMORTIGUADORES',
    text: 'Utilizar núcleos húmedos, circulaciones y espacios de servicio como franjas de amortiguación hacia el sur y el oeste.' },
  { code: 'T03', cat: 'T', group: 'Consideraciones generales', title: 'SERVICIOS AGRUPADOS',
    text: 'Concentrar núcleos húmedos y técnicos para optimizar instalaciones y reducir recorridos de cañerías.' },
  { code: 'T04', cat: 'T', group: 'Consideraciones generales', title: 'FLEXIBILIDAD DE USOS',
    text: 'Pensar espacios flexibles que admitan distintas configuraciones y cambios de uso según necesidades futuras, sin requerir modificaciones significativas de la estructura.' },
  { code: 'T05', cat: 'T', group: 'Consideraciones generales', title: 'POSIBILIDAD DE CRECIMIENTO',
    text: 'Prever áreas de expansión que permitan futuras ampliaciones de manera ordenada, garantizando la continuidad funcional y constructiva del proyecto.' },
  { code: 'T06', cat: 'T', group: 'Configuraciones tipológicas', title: 'COMPACTA',
    ventajas: ['Alta compacidad.', 'Mínima superficie de envolvente.', 'Menores pérdidas de calor.', 'Menor costo constructivo.', 'Circulaciones mínimas.'],
    desventajas: ['Menor iluminación en zonas centrales.', 'Restricciones en crecimiento (se limita solo a crecimiento vertical).'] },
  { code: 'T07', cat: 'T', group: 'Configuraciones tipológicas', title: 'LINEAL',
    ventajas: ['Óptima cuando el eje longitudinal se dispone en sentido Este-Oeste.', 'Buen aprovechamiento de ganancias solares e iluminación natural.', 'Mejora la relación con el exterior.', 'Optimiza la sectorización y organización de los espacios.'],
    desventajas: ['En lotes con eje norte-sur, procurar que el eje mayor del volumen no se exponga a la orientación oeste, debido a la complejidad del control solar.', 'Mayor superficie de envolvente exterior, aumentando las pérdidas y ganancias de calor.', 'Favorece recorridos longitudinales prolongados, con un consecuente incremento en los costos de construcción.'] },
  { code: 'T08', cat: 'T', group: 'Configuraciones tipológicas', title: 'EN L',
    ventajas: ['Adaptable a diferentes lotes y orientaciones.', 'Favorece la ventilación e iluminación de los espacios.', 'Optimiza la sectorización y organización de los espacios.', 'Capacidad de crecimiento manteniendo lógica del sistema lineal en alas.', 'Favorece la integración con los espacios exteriores.'],
    desventajas: ['Ganancias y pérdidas térmicas medio/alto si no se aprovecha la construcción lindera.', 'Incrementa la superficie de envolvente exterior, aumentando las pérdidas y ganancias térmicas.', 'Requiere una adecuada orientación de cada ala para optimizar el aprovechamiento solar y la ventilación natural.', 'Puede aumentar los recorridos entre espacios.'] },
  { code: 'T09', cat: 'T', group: 'Configuraciones tipológicas', title: 'FRAGMENTADA',
    ventajas: ['Favorece una implantación más adaptable al sitio, integrando los espacios construidos con el entorno.', 'Favorece la ventilación e iluminación de los espacios.', 'Favorece una organización funcional flexible, mediante una clara zonificación de los espacios.', 'Promueve la generación de espacios intermedios que fortalecen la relación entre el interior y el exterior.', 'Promueve configuraciones modulares innovadoras, con alta adaptabilidad y posibilidades de crecimiento.'],
    desventajas: ['Requiere una cuidadosa articulación entre los distintos volúmenes para garantizar una adecuada funcionalidad.', 'Puede aumentar la superficie de circulación y de conexión entre los distintos sectores.', 'Incrementa la complejidad constructiva en las uniones y encuentros entre volúmenes.', 'Puede aumentar la superficie de envolvente expuesta cuando los volúmenes se encuentran muy separados y sin una conexión mediante un espacio central.'] },

  // ============ 03 | ENVOLVENTES [EV] ============
  { code: 'EV01', cat: 'EV', group: 'Muro', title: 'Prefabricado de hormigón',
    capas: ['Pintura látex', 'Panel prefabricado de hormigón hueco', 'Pintura látex'],
    esp: '10cm', k: '4,32', iram: 'No cumple' },
  { code: 'EV02', cat: 'EV', group: 'Muro', title: 'Ladrillo común (12)',
    capas: ['Pintura látex', 'Revoque interior', 'Ladrillo ceramico macizo', 'Azotado hidrófugo', 'Revoque exterior'],
    esp: '17cm', k: '2,77', iram: 'No cumple' },
  { code: 'EV03', cat: 'EV', group: 'Muro', title: 'Ladrillo hueco (12)',
    capas: ['Revoque fino', 'Revoque grueso', 'Ladrillo cerámico hueco 12cm', 'Azotado hidrófugo', 'Revoque grueso', 'Texturado'],
    esp: '17cm', k: '1,74', iram: 'No cumple' },
  { code: 'EV04', cat: 'EV', group: 'Muro', title: 'Ladrillo hueco (18)',
    capas: ['Revoque fino', 'Revoque grueso', 'Ladrillo cerámico hueco 18 cm', 'Azotado hidrófugo', 'Revoque grueso', 'Texturado'],
    esp: '23cm', k: '1,60', iram: 'No cumple' },
  { code: 'EV05', cat: 'EV', group: 'Muro', title: 'Doble ladrillo común (30)',
    capas: ['Rev. Exterior completo', 'Ladrillo ceramico macizo (27cm)', 'Rev. interior completo'],
    esp: '30cm', k: '1,89', iram: 'No cumple' },
  { code: 'EV06', cat: 'EV', group: 'Muro', title: 'Doble ladrillo común + cámara de aire 3cm',
    capas: ['Ladrillo cerámico macizo', 'Azotado hidrófugo', 'Cámara de aire 3cm', 'Ladrillo cerámico macizo', 'Revoque grueso', 'Revoque fino'],
    esp: '33cm', k: '1,47', iram: 'Clase C' },
  { code: 'EV07', cat: 'EV', group: 'Muro', title: 'Ladrillo Hueco (18) + EIFS',
    capas: ['Revoque fino', 'Revoque grueso', 'Ladrillo hueco 18 cm', 'Azotado hidrófugo', 'Base coat', 'Placa EPS 25mm', 'Base coat y finish'],
    esp: '25cm', k: '0,76', iram: 'Clase B' },
  { code: 'EV08', cat: 'EV', group: 'Muro', title: 'Steel Framing',
    capas: ['Placa de yeso', 'Montante PGC 100', 'Lana de vidrio 100mm', 'Placa OSB', 'Barrera de agua y viento', 'Placa EPS 20mm', 'Base coat y finish'],
    esp: '15cm', k: '0,32', iram: 'Clase A',
    tip: 'Una pared de Steel Framing aisla 9 veces más que una de ladrillo común de similar espesor.[*nota-k]' },
  { code: 'EV09', cat: 'EV', group: 'Cubierta', title: 'Losa de hormigón armado (S/Aislación)',
    capas: ['Losa de hormigón armado 0,10 m', 'Film de polietileno', 'Contrapiso', 'Carpeta niveladora impermeable', 'Membrana hidrófuga'],
    esp: '20cm', k: '2,67', iram: 'No cumple' },
  { code: 'EV10', cat: 'EV', group: 'Cubierta', title: 'Chapa (S/Aislación)',
    capas: ['Placa de roca de yeso', 'Cámara de aire (30 cm)', 'Chapa sinusoidal'],
    esp: '31cm', k: '2,23', iram: 'No cumple' },
  { code: 'EV11', cat: 'EV', group: 'Cubierta', title: 'Chapa + 5 Cm lana de vidrio',
    capas: ['Placa de roca de yeso', 'Lana de vidrio 5 cm + barrera de vapor', 'Cámara de aire (30 cm)', 'Chapa sinusoidal'],
    esp: '36cm', k: '0,61', iram: 'Clase C' },
  { code: 'EV12', cat: 'EV', group: 'Cubierta', title: 'Chapa + (10+5) Cm lana de vidrio',
    capas: ['Placa roca de yeso', 'Lana de vidrio 10 cm + barrera de vapor', 'Placa rigidizadora OSB', 'Barrera de viento y agua Tyvek', 'Lana de vidrio (5 cm)', 'Chapa sinusoidal'],
    esp: '18cm', k: '0,26', iram: 'Clase B' },
  { code: 'EV13', cat: 'EV', group: 'Cubierta', title: 'Plana Steel Deck + aislación interior',
    capas: ['Placa roca de yeso', 'Lana de vidrio 5 cm + barrera de vapor', 'Chapa encofrado perdido', 'Capa de compresión', 'Contrapiso alivianado perlas EPS (5 cm)', 'Carpeta hidrófuga', 'Piso cerámico'],
    esp: '48cm', k: '0,49', iram: 'Clase C' },
  { code: 'EV14', cat: 'EV', group: 'Cubierta', title: 'Chapa + 10 Cm lana de vidrio',
    capas: ['Placa de roca de yeso', 'Lana de vidrio 10 cm', 'Cámara de aire (30 cm)', 'Chapa'],
    esp: '41cm', k: '0,36', iram: 'Clase B' },
  { code: 'EV15', cat: 'EV', group: 'Aventanamientos - consideraciones generales', title: 'CONTROL DE SUPERFICIE VIDRIADA',
    text: 'Regular la proporción entre vidrio y muro según orientación. Se debe disminuir la superficie vidriada evitando pérdidas térmicas.' },
  { code: 'EV16', cat: 'EV', group: 'Aventanamientos - consideraciones generales', title: 'CONTROL DE INFILTRACIONES',
    text: 'Incorporar ruptores de puente térmico (RPT) en carpinterías y burletes para reducir pérdidas energéticas.' },
  { code: 'EV17', cat: 'EV', group: 'Aventanamientos - consideraciones generales', title: 'ABERTURAS OPERABLES',
    text: 'Utilizar aberturas operables que permitan no solo la iluminación, sino también ventilación.' },
  { code: 'EV18', cat: 'EV', group: 'Aventanamientos - consideraciones generales', title: 'CAPAS',
    text: 'Utilizar “capas” (cortinas, vidrio, persianas, postigos) mejoran sustancialmente la eficiencia del aventanamiento tanto en invierno como en verano.' },
  { code: 'EV19', cat: 'EV', group: 'Aventanamientos - vidriado', title: 'VIDRIADO SIMPLE',
    text: 'Evitar colocar vidriado simple en locales de permanencia por la facilidad con que se producen ganancias y pérdidas calóricas.',
    kdato: 'K= 5,8 (W/m²K)' },
  { code: 'EV20', cat: 'EV', group: 'Aventanamientos - vidriado', title: 'DOBLE VIDRIADO HERMÉTICO (DVH) 4+12+4',
    text: 'Incorporar vidrios con cámara de aire hermética para mejorar la aislación térmica y evitar pérdidas del calor interior.',
    kdato: 'K= 2,9 (W/m²K)' },
  { code: 'EV21', cat: 'EV', group: 'Aventanamientos - vidriado', title: 'DOBLE VIDRIADO HERMÉTICO (DVH) LOW-E 4+12+4',
    text: 'Incorporar vidrios con tratamiento de baja emisividad (Low-E) para máxima protección frente a la radiación reflejando el calor y mejorando la aislación.',
    kdato: 'K=1,7 (W/m²K)',
    tip: 'La relación área ventana/muro óptima es de <b>40% de superficie vidriada hacia la orientación norte</b>[*dacunda], mientras que para el resto de las orientaciones es recomendable <b>no superar el 10%</b>.' },
  { code: 'EV22', cat: 'EV', group: 'Aventanamientos - marco', title: 'ALUMINIO SIN RPT',
    text: 'Evitar su uso en espacios habitables por ser un metal altamente conductor y carecer de barreras térmicas, transmitiendo directamente el frío exterior y puede producir condensación.' },
  { code: 'EV23', cat: 'EV', group: 'Aventanamientos - marco', title: 'ALUMINIO RPT',
    text: 'Incorporar RPT en espacios comunes o de presupuesto intermedio, para cortar la transmisión de temperatura, eliminando la condensación superficial y mejorando el confort higrotérmico.' },
  { code: 'EV24', cat: 'EV', group: 'Aventanamientos - marco', title: 'PVC',
    text: 'Incorporar marco de PVC, para el máximo rendimiento térmico y acústico. Priorizar su uso en dormitorios y orientaciones desfavorables.',
    tip: 'La utilización de DVH y persianas exteriores de PVC pueden <b>mejorar un 600%</b>[*nota-dvh] el rendimiento de una ventana con vidriado simple.' },

  // ============ 04 | SISTEMAS DE CONTROL Y PROTECCIÓN [P] ============
  { code: 'P01', cat: 'P', group: 'Horizontal', title: 'ALERO',
    text: 'Incorporar elementos fijos adosados (extensión de cubierta, alero independiente, etc.) opacos que permiten el sombreamiento controlado de la superficie. Recomendables en orientación norte.' },
  { code: 'P02', cat: 'P', group: 'Horizontal', title: 'PÉRGOLA',
    text: 'Disponer elementos horizontales de carácter permeables que permitan el ingreso de luz filtrada que produzcan condiciones de luz variables en los espacios, pudiendo también incorporar vegetación.' },
  { code: 'P03', cat: 'P', group: 'Horizontal', title: 'OPERABLE',
    text: 'Incorporar sistemas regulables (toldos, cubiertas pretensadas o elementos móviles) que permitan adaptarse según estación, clima o uso.' },
  { code: 'P04', cat: 'P', group: 'Vertical', title: 'PARASOL',
    text: 'Incorporar elementos verticales fijos o móviles en fachada para controlar la incidencia solar rasante. Recomendables principalmente en orientación Este-Oeste para reducir la incidencia solar de baja altitud.' },
  { code: 'P05', cat: 'P', group: 'Vertical', title: 'PERSIANAS',
    text: 'Disponer elementos verticales enrollables, para evitar pérdidas térmicas en invierno a través de los aventanamientos.' },
  { code: 'P06', cat: 'P', group: 'Vertical', title: 'CELOSÍA FIJA',
    text: 'Configurar planos permeables (cribado de ladrillos, mallas u otros sistemas) que regulen el ingreso de luz filtrada, viento y visuales según su grado de permeabilidad.' },
  { code: 'P07', cat: 'P', group: 'Vertical', title: 'ESCLUSA',
    text: 'Incorporar dispositivo móvil para permitir transformar la relación espacial entre locales, interior y exterior según condiciones de usos y temperaturas.' },
  { code: 'P08', cat: 'P', group: 'Vertical', title: 'OPERABLE',
    text: 'Incorporar sistemas regulables que permitan ajustar la apertura y el nivel de protección según condiciones de uso y clima.' },
  { code: 'P09', cat: 'P', group: 'Vegetación', title: 'SUELOS VEGETADOS',
    text: 'Sustituir superficies inertes por suelos vegetados para reducir la reflexión térmica, mejorar la infiltración de agua en el terreno y mejorar las condiciones ambientales.' },
  { code: 'P10', cat: 'P', group: 'Vegetación', title: 'VEGETACIÓN CADUCA',
    text: 'Incorporar especies de este tipo para generar sombra en verano e ingreso de radiación solar en invierno.' },
  { code: 'P11', cat: 'P', group: 'Vegetación', title: 'VEGETACIÓN PERENNE',
    text: 'Incorporar especies de follaje permanente para protección solar sobre orientación Oeste, control de visuales y de ventilación.' },
  { code: 'P12', cat: 'P', group: 'Vegetación', title: 'JARDINES VERTICALES',
    text: 'Ubicar capas vegetales sobre las envolventes o protecciones solares para regular la radiación solar, la temperatura, el viento, el ruido y la permeabilidad visual.' },
  { code: 'P13', cat: 'P', group: 'Vegetación', title: 'CUBIERTAS VERDES',
    text: 'Disponer una capa vegetal para reducir la temperatura de la cubierta, retener el agua de lluvia y crear espacios verdes que sirvan como hábitat de especies.' },

  // ============ 05 | SISTEMAS COMPLEMENTARIOS [SC] ============
  { code: 'SC01', cat: 'SC', group: '', title: 'CHIMENEA SOLAR',
    text: 'Implementar este sistema para favorecer la extracción del aire caliente y viciado de los espacios, utilizando la diferencia de presión para succionarlo hacia arriba' },
  { code: 'SC02', cat: 'SC', group: '', title: 'GEOTERMIA',
    text: 'Implementar este sistema para reducir la demanda de climatización, utilizando la inercia térmica del suelo, que se mantiene a temperatura relativamente constante, para calentar/enfriar aire según la estación.' },

  // ============ 06 | ARTEFACTOS EFICIENTES [AE] ============
  { code: 'AE01', cat: 'AE', group: '', title: 'AGUA',
    text: 'Utilizar griferías con aireadores, inodoros de doble descarga, duchas de caudal limitado pudiendo disminuir un 54% el consumo de agua.',
    tabla: {
      headers: ['Cant.', 'Artefacto', 'Tiempo/Frecuencia', 'Consumo por unidad (L)', 'Día Entero (L)'],
      tradicionales: [
        ['Ducha', '6m (uso diario)', '10 L/min', '60'],
        ['Griferías baño', '3m / 5m', '7 L/min', '35'],
        ['Griferías cocina', '4m / 8m', '8 L/min', '64'],
        ['Inodoros', '3v / 5v', '8 L/descarga', '40'],
        ['Lavarropas', '0,4v / 0,4v', '100 L/carga', '100'],
      ],
      totalTradicionales: '299',
      eficientes: [
        ['Ducha', '6m (uso diario)', '6 L/min', '36'],
        ['Griferías baño', '3m / 5m', '3 L/min', '15'],
        ['Griferías cocina', '4m / 8m', '6 L/min', '48'],
        ['Inodoro (N°1)', '2v / 4v', '3 L/descarga', '12'],
        ['Inodoro (N°2)', '1v / 1v', '6 L/descarga', '6'],
        ['Lavarropas', '0,4v / 0,4v', '20 L/carga', '20'],
      ],
      totalEficientes: '137',
      caption: 'Tabla 1: Consumo de artefactos, tradicionales vs eficientes.\nFuente: Barreneche R. (2017)[*barreneche]. Elaboración: Propia',
      // Misma tabla, emparejada artefacto por artefacto para el gráfico comparativo.
      // "dia" = litros por día entero. El inodoro eficiente suma sus dos descargas.
      pares: [
        { artefacto: 'Ducha', mejora: 'de caudal limitado',
          trad: { unidad: '10 L/min', dia: 60 }, efic: { unidad: '6 L/min', dia: 36 } },
        { artefacto: 'Griferías baño', mejora: 'con aireadores',
          trad: { unidad: '7 L/min', dia: 35 }, efic: { unidad: '3 L/min', dia: 15 } },
        { artefacto: 'Griferías cocina', mejora: 'con aireadores',
          trad: { unidad: '8 L/min', dia: 64 }, efic: { unidad: '6 L/min', dia: 48 } },
        { artefacto: 'Inodoro', mejora: 'de doble descarga',
          trad: { unidad: '8 L/descarga', dia: 40 }, efic: { unidad: '3 L y 6 L/descarga', dia: 18 } },
        { artefacto: 'Lavarropas', mejora: 'eficiente',
          trad: { unidad: '100 L/carga', dia: 100 }, efic: { unidad: '20 L/carga', dia: 20 } },
      ],
    } },
  { code: 'AE02', cat: 'AE', group: '', title: 'TECNOLOGÍA INVERTER',
    text: 'Priorizar la utilización de estos equipos para eliminar los picos de consumo eléctrico producidos durante los arranque del motor y mantener una estabilidad térmica constante. Reduciendo el consumo energético entre un 35-50%, aumentan el confort y la vida útil.' },
  { code: 'AE03', cat: 'AE', group: '', title: 'AEROTERMIA',
    text: 'Aprovechar la energía térmica del exterior mediante una bomba de calor para proporcionar calefacción, refrigeración y agua caliente.',
    ventajas: ['Alta compacidad.', 'Mínima superficie de envolvente.', 'Por cada 1 kW de electricidad consumida, pueden generar 4 kW de energía térmica, es decir una eficiencia del 400%', 'Menor costo constructivo.', 'Circulaciones mínimas.'],
    desventajas: ['Inversión inicial elevada en comparación a los sistemas más utilizados de calefacción como los calefactores a gas o los aires acondicionados.', 'Unidad exterior voluminosa: Se debe contemplar un espacio exterior que permita el flujo del aire, teniendo en cuenta que el equipo emite ruidos y vibraciones.', 'Necesidad de una sala técnica de aproximadamente 2 a 4 m² con ventilación.'],
    ciclo: {
      intro: 'Funciona mediante un ciclo termodinámico de 4 pasos con un gas refrigerante:',
      pasos: [
        ['(1). Evaporación (Captación):', 'El aire exterior pasa por el evaporador. El refrigerante, que entra muy frío, roba calor del aire y se evapora (se convierte en gas).'],
        ['(2). Compresión (Consumo):', 'El compresor eléctrico aplasta ese gas. Al aumentar la presión, su temperatura se dispara. Aquí es donde "gastamos" electricidad.'],
        ['(3). Condensación (Cesión):', 'Ese gas caliente cede su calor al agua del circuito de calefacción de la casa. Al enfriarse, vuelve a estado líquido.'],
        ['(4). Expansión:', 'El líquido pasa por una válvula que libera la presión bruscamente, enfriándolo (como un spray desodorante al salir), quedando listo para volver a robar calor afuera.'],
      ] } },
  { code: 'AE04', cat: 'AE', group: '', title: 'CALDERA DE CONDENSACIÓN',
    text: 'Aprovechar la energía térmica del exterior incorporando una bomba de calor para proporcionar calefacción, refrigeración y agua caliente.',
    ventajas: ['Ahorro entre 25 y 35% de gas en comparación con un calefactor de tiro balanceado.'],
    desventajas: ['Se debe prever un sistema de desagüe: Puede generar entre 1 y 2 litros de agua por hora de funcionamiento.', 'Costo inicial más elevado que un sistema de calefacción de tiro balanceado, pero mucho más barato que el de la Geotermia y la Aerotermia.'],
    ciclo: {
      intro: 'Funciona mediante un ciclo termodinámico de 4 pasos con un gas refrigerante:',
      pasos: [
        ['(1). Mezcla y combustión:', 'El gas y el aire ingresan a la cámara para alimentar el quemador y generar la llama directa.'],
        ['(2). Ingreso del retorno frío:', 'El agua del circuito de calefacción regresa fría a la caldera por la tubería de Retorno de agua.'],
        ['(3). Recuperación de calor latente:', 'Al pasar por el serpentín secundario, el agua fría enfría los humos de la combustión. El vapor de agua que estos contienen se condensa, liberando energía térmica que precalienta el circuito.'],
        ['(4). Evacuación de condensados:', 'El agua líquida resultante del proceso de condensación se drena por la salida inferior de Condensación.'],
        ['(5). Calentamiento final e inyección:', 'El agua precalentada avanza hacia el intercambiador principal sobre la llama directa, alcanza la temperatura de diseño y sale impulsada a la red por la Inyección de agua.'],
        ['(6). Escape de humos limpios:', 'Los gases de combustión, ya despojados de la mayor parte de su calor y humedad, son expulsados a baja temperatura como Gas de condensación (humos residuales).'],
      ] } },

  // ============ 07 | ENERGÍAS RENOVABLES [ER] ============
  { code: 'ER01', cat: 'ER', group: 'Energía Fotovoltaica y solar', title: 'SISTEMAS ON GRID',
    text: 'Implementar sistema conectado a la red para que la vivienda consuma la energía que genere e inyecte los excedentes a la red pública, sin requerir baterías (menor costo y mantenimiento).' },
  { code: 'ER02', cat: 'ER', group: 'Energía Fotovoltaica y solar', title: 'SISTEMAS OFF GRID',
    text: 'Disponer sistema aislado de la red eléctrica para alcanzar autonomía energética, mediante un banco de baterías que implica un mayor costo y mantenimiento, recomendado para zonas rurales o donde no exista acceso a la red.' },
  { code: 'ER03', cat: 'ER', group: 'Energía Fotovoltaica y solar', title: 'TERMOTANQUE SOLAR',
    text: 'Aprovechar la energía solar para el calentamiento de agua de uso sanitario, calefacción y acondicionamiento térmico de piscinas.',
    // "notas": avisos generales de la subcategoría. Se renderizan al pie del grupo
    // (debajo de la línea de las fichas), no dentro de la ficha. "icon" reemplaza al foquito.
    notas: [
      { icon: 'assets/er/prosumidores.png', alt: 'Programa Prosumidores de Santa Fe', link: 'https://www.santafe.gob.ar/ms/prosumidores/',
        html: 'En la provincia de Santa Fe existe un programa llamado <b>“Prosumidores”</b> que permite generar energía renovable para auto consumo y vender la producción de energía excedente a la Empresa Provincial de la Energía (EPE). Además ofrecen reconocimientos económicos y créditos de inversión para la transición energética de energías renovables' },
      { icon: 'assets/er/paneles.png', alt: 'Panel solar con 32° de inclinación',
        html: 'Los <b>paneles solares</b> buscan aprovechar la mayor cantidad de radiación durante todo el año. Se recomienda orientación norte, y una <b>inclinación de 32°</b> (próxima a la latitud local).' },
      { icon: 'assets/er/termotanques.png', alt: 'Termotanque solar con 45° de inclinación',
        html: 'Los <b>termotanques</b> buscan garantizar el suministro en la época desfavorable (invierno) y prevenir riesgos operativos por sobretemperatura en verano. Se recomienda orientación norte, y una <b>inclinación de 45°</b>.' },
    ] },

  // ============ 08 | GESTIÓN DEL RECURSO HÍDRICO [RH] ============
  { code: 'RH01', cat: 'RH', group: '', title: 'REUTILIZACIÓN DE AGUAS GRISES',
    text: 'Reutilizar aguas de duchas, bañeras y lavamanos, posterior al tratamiento, para la descarga de inodoros, lavado y riego.' },
  { code: 'RH02', cat: 'RH', group: '', title: 'TRATAMIENTO DE AGUAS NEGRAS',
    text: 'Reutilizar aguas negras (inodoro), posterior a un tratamiento complejo, para uso de riego.' },
  { code: 'RH03', cat: 'RH', group: '', title: 'APROVECHAMIENTO DE AGUA DE LLUVIA',
    text: 'Almacenar agua de las cubiertas y utilizarla para lavar ropa, descargar inodoros, limpieza de pisos o regar.',
    tip: 'Reutilizando agua de lluvia, en una cubierta de 100 m2 podemos captar <b>90.000 litros de agua</b> anuales, ésto equivale a 41 descargas de inodoro diarias durante todo un año.[*nota-lluvia]' },
];

// Texto introductorio de la sección Vegetación (04 | P)
const VEGETACION_EXTRA = {
  intro: 'La incorporación estratégica de vegetación en el proyecto y su entorno inmediato aporta ventajas claves para el hábitat:',
  items: [
    ['Enfriamiento evaporativo:', 'Baja la temperatura del aire circundante por evapotranspiración, optimizando el microclima.'],
    ['Control lumínico:', 'Filtra la radiación solar directa y disminuye el deslumbramiento, mejorando el confort visual.'],
    ['Barrera acústica y ambiental:', 'Amortigua ruidos urbanos y colabora en la purificación del aire al retener material particulado.'],
    ['Privacidad visual:', 'Configura límites virtuales y protección de vistas sin obstruir las corrientes de ventilación natural.'],
    ['Confort psicológico:', 'Estimula el bienestar psicofísico de los usuarios a través de la integración biofílica con el paisaje.'],
  ],
  cierre: 'El uso prioritario de especies nativas actúa como un vector ecológico y cultural que preserva la biodiversidad local, restaura el paisaje original y demanda un menor mantenimiento hídrico en el territorio.',
  tip: 'Algunas <b>especies recomendadas</b>[*broda] para viviendas en nuestra ecorregión son el Ñangapirí, Palo Jabón, Tala, Sangre de Drago, Espinillo, Jacarandá, Lapacho Amarillo y Curupi.',
};

// Intro de la sección 03 | Envolventes (consideraciones generales sobre color)
const ENVOLVENTES_COLOR = {
  p1: 'El <b>color</b> en las envolventes (techos, muros) tiene una influencia importante en el comportamiento térmico de una vivienda, ya que determina cuánta radiación solar absorben o reflejan las superficies.',
  oscuros: { label: 'Colores oscuros', sub: '(negro, gris oscuro, marrón oscuro)',
    items: ['Absorben una mayor proporción de la radiación solar.', 'Alcanzan temperaturas superficiales más elevadas.', 'Incrementan la transferencia de calor hacia el interior.', 'Pueden ser beneficiosos en climas fríos donde se busca aprovechar la ganancia solar.'] },
  claros: { label: 'Colores claros', sub: '(blanco, beige, gris claro)',
    items: ['Reflejan gran parte de la radiación solar.', 'Mantienen temperaturas superficiales más bajas.', 'Reducen las ganancias térmicas hacia el interior.', 'Son especialmente útiles en climas cálidos.'] },
  p2: 'Estudios han demostrado[*frei] que las cubiertas claras pueden presentar temperaturas superficiales entre 20 y 30°C inferiores que cubiertas oscuras expuestas a las mismas condiciones de radiación solar.',
  p3: 'En la cubierta es donde el color tiene mayor impacto, porque reciben la mayor cantidad de radiación, aunque los muros también se ven altamente afectados. En ambos casos, para nuestra región es siempre recomendable utilizar colores claros.',
};

// Intro de la sección 08 | RH
const RH_INTRO = 'Según la subsecretaría de Ambiente y Desarrollo Sustentable de la nación, en Argentina, el consumo doméstico de agua es en promedio de 318 litros por habitante por día. Esto significa un 83% más que la media latinoamericana y 6,3 veces más que los estándares fijados por la OMS.[*gonzalez]\n\nLas siguientes estrategias contribuyen a disminuir considerablemente el consumo';

// Referencias del ANEXO I (notas al pie 1-13 del PDF + bibliografía final).
// En cualquier texto, "[*clave]" se convierte en un asterisco que muestra la
// referencia al pasar el mouse. bib: true = figura en "Bibliografía"; si no, es
// una nota o fuente complementaria. El orden de la lista es el del PDF.
const REFS = {
  bardou: { bib: true, html: 'Bardou, P. y Arzoumanian V. (1981). <i>Sol y Arquitectura.</i> Gustavo Gili.' },
  czajkowski: { bib: true, html: 'Czajkowski J.D. y Gómez, A. F. (2009). <i>Arquitectura sustentable.</i> Colección: Herramientas para Arquitectos. AGEA.' },
  iram11601: { bib: true, html: 'Instituto Argentino de Normalización y Certificación (IRAM) (2002). <i>Acondicionamiento térmico de edificios. Propiedades térmicas de los componentes y elementos de construcción en régimen estacionario.</i> (IRAM 11601:2002). IRAM.' },
  puig: { bib: true, html: 'Puig, S. E. (2023) Estrategias de intervención tecnológica. <i>Evaluación del desempeño energético en viviendas sociales de la Provincia de Santa Fe.</i> [Tesis de Maestría, Universidad Nacional del Litoral, Facultad de Arquitectura, Diseño y Urbanismo]. Biblioteca Virtual UNL. https://hdl.handle.net/11185/7642' },
  frei: { bib: true, html: 'Frei, A. (2023). Thermal properties of green, white, and other roofing materials, and solar insolation: A case study in New York City. <i>Building and Environment, 244</i>, 110842. https://doi.org/10.1016/j.buildenv.2023.110842' },
  dacunda: { bib: true, html: 'Dacunda, M. (2024). <i>Evaluación de la eficiencia energética de edificios residenciales : recomendaciones y propuestas de mejoras.</i> [Proyecto Final de Carrera, Universidad Tecnológica Nacional, Facultad Regional Santa Fe]. Repositorio Institucional Abierto (RIA-UTN). https://hdl.handle.net/20.500.12272/11854' },
  barreneche: { bib: true, html: 'Barreneche, R. O. (2017). <i>Instalaciones Sanitarias Sostenibles.</i> Diseño Editorial.' },
  gonzalez: { bib: true, html: 'González Calderón, J. (2019). <i>Manual de vivienda sustentable.</i> Ministerio de Interior, Obras Públicas y Vivienda. Secretaría de ambiente y desarrollo sustentable. Secretaría de Energía. Presidencia de la Nación Argentina.' },

  'resolucion-pronev': { bib: true, html: 'Resolución N°5/2023 de la Secretaría de Energía del Ministerio de Economía.' },
  'nota-k': { html: 'Considerando los valores de transmitancia térmica (K) mencionados anteriormente.' },
  'nota-dvh': { html: 'Considerando un vidrio simple de K= 5,8 W/m²K y un paquete de Ventana, DVH y persiana de 15 mm con poliuretano de alta densidad, K= 0,97 W/m²K.' },
  broda: { html: 'Colaboración personal del ingeniero agrónomo Ruben Broda.' },
  'nota-lluvia': { html: 'Considerando un régimen pluviométrico aproximado de 1000 mm anuales, precipitación media anual de los últimos diez años (2016-2025). Datos meteorológicos del CIM FICH UNL. Recuperado de http://wfich1.unl.edu.ar/cim/datos-meteorologicos el 12 de enero de 2026.' },
};



// Bibliografía completa: la del final de la Memoria Conceptual de la tesis más
// las citadas en el Anexo I. Ordenada alfabéticamente. Las entradas con "ref"
// son las que algún asterisco del manual señala: comparten el id con REFS, así
// el enlace "Ver en Bibliografía y fuentes" cae en la entrada correcta.
const BIBLIOGRAFIA = [
  { html: 'Alconchel, M. V. (2018). <i>El hábitat social colectivo. Estrategias para su rehabilitación.</i> [Tesis de Maestría, Universidad Nacional del Litoral, Facultad de Arquitectura, Diseño y Urbanismo]. Biblioteca Virtual UNL. http://hdl.handle.net/11185/1208' },
  { html: 'American Society of Heating, Refrigerating and Air-Conditioning Engineers (ASHRAE) (2010). <i>Thermal Environmental Conditions for Human Occupancy. ASHRAE Standard 55-2010.</i>' },
  { html: 'Argan, G. C. (1973). <i>El concepto del espacio arquitectónico: desde el Barroco a nuestros días.</i> Nueva Visión.' },
  { html: 'Baker, N. V. y Steemers, K. (1995). <i>The LT method 2.0: An energy design tool for non-domestic buildings.</i> Cambridge Architectural Research.' },
  { ref: 'bardou', html: 'Bardou, P. y Arzoumanian, V. (1981). <i>Sol y Arquitectura.</i> Editorial Gustavo Gili.' },
  { ref: 'barreneche', html: 'Barreneche, R. O. (2017). <i>Instalaciones Sanitarias Sostenibles.</i> Diseño Editorial.' },
  { html: 'Benet, J. A. (Dir.). (2026, mayo). CIFRAS. <i>La Revista de la Construcción</i> (Año 37, N.º 362). Estudio Tres Arquitectos y Asociados. https://www.cifrasonline.com.ar' },
  { html: 'Betti, G., Tartarini, F., Nguyen, C. y Schiavon, S. (2023). <i>CBE Clima Tool: A free and open-source web application for climate analysis tailored to sustainable building design.</i> Building Simulation. Universidad de Cornell.' },
  { html: 'Bosi, M.; Fontanetto, L. y Tate, M. V. (2022). <i>Rehabilitación edilicia bioclimática: Análisis de los niveles de confort bajo las condiciones de eficiencia energética. El caso del edificio el Cubo en la ciudad universitaria de Santa Fe.</i> [Tesis de Grado, Universidad Nacional del Litoral, Facultad de Arquitectura, Diseño y Urbanismo]. Biblioteca Virtual UNL. http://hdl.handle.net/11185/2046' },
  { html: 'Brundtland, G. H. (1987). <i>Nuestro futuro común: Informe de la Comisión Mundial sobre el Medio Ambiente y el Desarrollo.</i> Documento de las Naciones Unidas A/42/427.' },
  { html: 'Carli, C. (2003). <i>8° al Sur del Trópico de Capricornio.</i> Editorial Kliczkowski.' },
  { html: 'Casañas, S. F.; Perez, B. S. y Villaraza, S. G. (2024). <i>Habitabilidad, rehabilitación energética y arquitectónica en conjuntos habitacionales FONAVI de Santa Fe. Caso: Barrio el Pozo.</i> [Tesis de Grado, Universidad Nacional del Litoral, Facultad de Arquitectura, Diseño y Urbanismo].' },
  { html: 'Ching, F. D. K. y Shapiro, I. M. (2015). <i>Arquitectura ecológica un manual ilustrado.</i> Editorial GG.' },
  { html: 'Concejo Municipal San Carlos Centro. (2018). <i>Ordenanza N° 944/19.</i>' },
  { html: 'Conarquitectura. (2013). <i>Conarquitectura</i> (N.º 48, Eficiencia energética). Conarquitectura Ediciones. https://issuu.com/conarquitectura/docs/ca48_issuu' },
  { html: 'Czajkowski, J. D. y Gómez, A. F. (2002). <i>Diseño bioclimático y economía energética edilicia.</i> Universidad Nacional de La Plata.' },
  { ref: 'czajkowski', html: 'Czajkowski, J. D. y Gómez, A. F. (2009). <i>Arquitectura sustentable.</i> Colección: Herramientas para Arquitectos. AGEA.' },
  { html: 'Czajkowski, J. D. y Gómez, A. F. (2023). <i>Ciudades sustentables, una forma de amigarnos con el ambiente.</i> Laboratorio de Arquitectura y Hábitat Sustentable. Universidad Nacional de La Plata.' },
  { html: 'Czajkowski, J. D. (2025, 24 de abril). <i>Determinación de la demanda de energía de una vivienda prefabricada con Inteligencia Artificial y su mejoramiento.</i> SEDICI, UNLP. http://sedici.unlp.edu.ar/handle/10915/178492' },
  { ref: 'dacunda', html: 'Dacunda, M. (2024). <i>Evaluación de la eficiencia energética de edificios residenciales : recomendaciones y propuestas de mejoras.</i> [Proyecto Final de Carrera, Universidad Tecnológica Nacional, Facultad Regional Santa Fe]. Repositorio Institucional Abierto (RIA-UTN). https://hdl.handle.net/20.500.12272/11854' },
  { html: 'De Garrido, L. (2017). <i>Manual de Arquitectura Ecológica Avanzada. Metodología de diseño para realizar una arquitectura con el máximo nivel ecológico posible.</i> Diseño Editorial.' },
  { html: 'Dona, L. (2024). <i>Análisis energético de vivienda social. San Carlos Sud. Santa Fe. Argentina.</i> DOI: 10.13140/RG.2.2.33103.91042' },
  { html: 'Edwards, B. y Hyett, P. (2004). <i>Guía Básica de la Sostenibilidad.</i> Editorial Gustavo Gilli.' },
  { html: 'Evans, J. M. y Schiller, S. (1994). <i>Diseño Bioambiental y Arquitectura Solar.</i> Editorial UBA.' },
  { html: 'Ferrando, R. V. y Gutiérrez Garigliano, M. R. (2008). <i>Edificación Energéticamente Sustentable en la Ciudad de Santa Fe.</i> [Tesis de Grado no publicada, Universidad Nacional del Litoral, Facultad de Arquitectura, Diseño y Urbanismo].' },
  { html: 'Filippín, C. y Larsen, S. F. (2012). <i>Summer thermal behaviour of compact single family housing in a temperate climate in Argentina.</i> Renewable And Sustainable Energy Reviews. http://dx.doi.org/10.1016/j.rser.2012.01.060' },
  { ref: 'frei', html: 'Frei, A. (2023). Thermal properties of green, white, and other roofing materials, and solar insolation: A case study in New York City. <i>Building and Environment, 244</i>, 110842. https://doi.org/10.1016/j.buildenv.2023.110842' },
  { html: 'Garganta, M. L. (2015). <i>Proyecto de vivienda unifamiliar bioclimático en la ciudad de la plata, buenos aires. Pautas de diseño, eficiencia y evaluación energética.</i> [Tesis de Maestría en Arquitectura y Hábitat Sustentable, Facultad de Arquitectura, Universidad Nacional de La Plata]. SEDICI, UNLP. http://sedici.unlp.edu.ar/handle/10915/62826' },
  { html: 'Garzón, B. (2007). <i>Arquitectura Bioclimática.</i> Nobuko.' },
  { ref: 'gonzalez', html: 'González Calderón, J. (2019). <i>Manual de vivienda sustentable.</i> Ministerio de Interior, Obras Públicas y Vivienda. Secretaría de ambiente y desarrollo sustentable. Secretaría de Energía. Presidencia de la Nación Argentina.' },
  { html: 'Gonzalo, G. E. (2003). <i>Manual de Arquitectura Bioclimática y Sustentable.</i> 5ta Edición. Nobuko.' },
  { html: 'Grossi Gallegos, H. y Righini, R. (2007). <i>Atlas de Energía Solar de la República Argentina.</i> Secretaría de ciencia, tecnología e innovación productiva. Universidad Nacional de Luján.' },
  { html: 'Gutiérrez González, S. (2023). <i>Estrategias bioclimáticas en la arquitectura de Ruiz-Larrea.</i> Universidad Politécnica de Madrid.' },
  { html: 'Habraken, N. J. (1975). <i>Soportes: una alternativa al alojamiento de masas.</i> Alberto Corazón.' },
  { html: 'Hernández Pezzi, C. (2007). <i>Un Vitruvio ecológico: bases para un nuevo paradigma en la arquitectura.</i> Editorial Gustavo Gili.' },
  { html: 'Instituto Argentino de Normalización y Certificación (IRAM) (1996). <i>Acondicionamiento térmico de edificios. Condiciones de habitabilidad en edificios.</i> (IRAM 11605:1996). IRAM.' },
  { ref: 'iram11601', html: 'Instituto Argentino de Normalización y Certificación (IRAM) (2002). <i>Acondicionamiento térmico de edificios. Propiedades térmicas de los componentes y elementos de construcción en régimen estacionario.</i> (IRAM 11601:2002). IRAM.' },
  { html: 'Instituto Argentino de Normalización y Certificación (IRAM) (2004). <i>Acondicionamiento térmico de edificios. Verificación de sus condiciones higrotérmicas. Ahorro de energía en refrigeración.</i> (IRAM 11659:2004). IRAM.' },
  { html: 'Instituto Argentino de Normalización y Certificación (IRAM) (2011). <i>Acondicionamiento térmico de edificios. Clasificación bioambiental de la República Argentina.</i> (IRAM 11603:2011). IRAM.' },
  { html: 'Instituto Nacional de Estadística y Censos (INDEC) (2023). <i>Censo Nacional de Población, Hogares y Viviendas 2022: Resultados definitivos.</i> https://www.indec.gob.ar/indec/web/Nivel4-Tema-2-41-165' },
  { html: 'Lamberts, R., Ghisi, E., Pereira, C. D. y Batista, J. O. (Eds.). (2010). <i>Casa eficiente: Bioclimatologia e desempenho térmico</i> (Vol. 1); <i>Consumo e geração de energia</i> (Vol. 2); <i>Uso racional da água</i> (Vol. 3); <i>Simulação Computacional do Desempenho Termo-Energético</i> (Vol. 4). UFSC/LabEEE.' },
  { html: 'Lara, E. (2019). Oasis urbano: Una propuesta de acondicionamiento térmico para el metro de Santiago. <i>Revista Hábitat Sustentable</i>, 9(2), 16-29. https://doi.org/10.22320/07190700.2019.09.02.02' },
  { html: 'Lindsey, L. (2024). <i>La evidencia del cambio climático.</i> NASA Science. https://ciencia.nasa.gov/cambio-climatico/evidencia/' },
  { html: 'Moneo, R. (1978). On Typology. <i>Oppositions</i>, no. 13 (Summer 1978): 22-45.' },
  { html: 'Montaner, J. M. y Muxí Martínez, Z. (2006). <i>Habitar el presente. Vivienda en España: sociedad, ciudad, tecnología y recursos.</i> Ministerio de Vivienda.' },
  { html: 'Municipalidad de San Carlos Centro. (1982). <i>Reglamento General de Edificación.</i>' },
  { html: 'Neila, F. J. (2004). <i>Arquitectura bioclimática en un entorno sostenible.</i> Ed. Munilla-Lería.' },
  { html: 'Objetivos de desarrollo sostenible. (s. f.). UNDP. https://www.undp.org/es/' },
  { html: 'Olgyay, V. (2019). <i>Arquitectura y Clima. Manual de diseño bioclimático para arquitectos y urbanistas.</i> Editorial Gustavo Gili.' },
  { html: 'Prieto, E. (2011). <i>La Arquitectura de la ciudad global. Redes, no-lugares, naturaleza.</i> Editorial Biblioteca Nueva.' },
  { html: 'Provincia de Santa Fe (2019). <i>Ley N.º 13.903. Etiquetado de eficiencia energética de inmuebles destinados a vivienda.</i> Boletín Oficial de la Provincia de Santa Fe.' },
  { html: 'Provincia de Santa Fe (s. f.). <i>Prosumidores.</i> Somos Energía. https://www.santafe.gob.ar/ms/prosumidores/' },
  { html: 'Puig, S. E. y San Juan, G. (2020). Intervención tecnológica en la vivienda social para maximizar la eficiencia energética, aplicando el índice de prestaciones energéticas (IPE). Caso de estudio: vivienda universal, Santa Fe, Argentina. <i>Energías Renovables y Medio Ambiente</i>, 46, 1-13. http://hdl.handle.net/11336/154665' },
  { html: 'Puig, S. E., Alberini, R. S. y Eggel, A. (2021). Viviendas sociales de la Ciudad de Santa Fe. Cómo mejorar su Etiqueta de Eficiencia Energética. Caso de estudio: Vivienda Universal. <i>Arquitecno</i>, (18), 115–123. https://doi.org/10.30972/arq.0185675' },
  { ref: 'puig', html: 'Puig, S. E. (2023) Estrategias de intervención tecnológica. <i>Evaluación del desempeño energético en viviendas sociales de la Provincia de Santa Fe.</i> [Tesis de Maestría, Universidad Nacional del Litoral, Facultad de Arquitectura, Diseño y Urbanismo]. Biblioteca Virtual UNL. https://hdl.handle.net/11185/7642' },
  { html: 'Raya, M. O. y Salinas, M. E. (2021). <i>Parámetros sustentables que complementan el “etiquetado de eficiencia energética en inmuebles destinados a viviendas” para proyectos de obra nueva en edificios de renta de media densidad en la ciudad de Santa Fe.</i> [Tesis de Grado, Universidad Nacional del Litoral, Facultad de Arquitectura, Diseño y Urbanismo].' },
  { html: 'Rosenfeld, E., Czajkowski, J. y San Juan, G. (2004). Arquitectura Bioclimática. En Liernur, J. F. y Aliata, F. (Comps.), <i>Diccionario de Arquitectura en la Argentina.</i> Tomo a-b. AGEA.' },
  { html: 'Rosenfeld, E., Guerrero, J. L. y Ravella, O. R. (2009). <i>La casa solar de La Plata.</i> Facultad de Arquitectura y Urbanismo, UNLP. https://sedici.unlp.edu.ar/handle/10915/57307' },
  { html: 'San Juan, G. (2013) <i>Diseño bioclimático, como aporte al proyecto arquitectónico.</i> Libros de Cátedra Universidad Nacional de La Plata. Editorial Edulp.' },
  { html: 'Secretaría de Energía. (s. f.). <i>Transición y Planeamiento Energético.</i> Gobierno de Argentina. Recuperado el 13 de febrero de 2026, de https://www.argentina.gob.ar/economia/energia/transicion-planeamiento-energetico' },
  { ref: 'resolucion-pronev', html: 'Secretaría de Energía. (2023, 6 de enero). <i>Resolución 5/2023. Programa Nacional de Etiquetado de Viviendas (PRONEV).</i> Boletín Oficial de la República Argentina.' },
  { html: 'Souto de Moura, E. (2007). La buena arquitectura lleva implícito el ser sostenible / Entrevistado por A. Zabalbeascoa. <i>Revista Babelia.</i>' },
  { html: 'Stagnitta, R., comunicación personal, mayo de 2025.' },
  { html: 'Terrados-Cepeda, F. J., Baco-Castro, L. y Moreno-Rangel, D. (2015). Patio 2.12: Vivienda prefabricada, sostenible, autosuficiente y energéticamente eficiente. Participación en la competición Solar Decathlon Europe 2012. <i>Informes De La Construcción</i>, 67(538), e088. https://doi.org/10.3989/ic.13.138' },
  { html: 'Tourn, H. A. (2022). <i>Cronología de la inmigración italiana en la Colonia San Carlos. 1850–1950.</i> Tourn.' },
  { html: 'Vergara, E. (2025). Construir en tiempos de crisis: repensar las políticas públicas hacia ciudades regenerativas. En <i>Ciudades Regenerativas.</i> CAPBA N° 21.' },
  { html: 'Ward, B. y Dubos, R. (1972). <i>Una Sola Tierra. El cuidado y conservación de un pequeño planeta.</i> Fondo de Cultura Económica.' },
  { html: 'Zuo, J. y Zhao, Z. (2014). <i>Green Building Research-Current Status and Future Agenda.</i> Renewable and Sustainable Energy Reviews, 30, 271-281. https://doi.org/10.1016/j.rser.2013.10.021' },
];
